groups: load group topics from Tox save
uTox/uTox pull request #1492
Opened 2020-11-24 01:38 UTC by avoidr

2020-11-24 23:49 UTC, robinlinden requested changes

2020-11-24 23:49 UTC, robinlinden commented on src/groups.c
> +GROUPCHAT *group_create(uint32_t group_number, bool av_group, char *name) {
const char *?

2020-11-24 23:49 UTC, robinlinden commented on src/groups.c
> +void group_init(GROUPCHAT *g, uint32_t group_number, bool av_group, char *name) {
const char *?

2020-11-24 23:49 UTC, robinlinden commented on src/groups.c
> +        snprintf((char *)g->name, sizeof(g->name), "Groupchat #%u", group_number);
Useless cast

2020-11-24 23:49 UTC, robinlinden commented on src/groups.c
> +        g->name_length = strnlen(g->name, sizeof(g->name) - 1);
strnlen isn't in the C standard. You can (probably) use strnlen_s if uTox targets C11. (Or use strlen since you know g->name always is null-terminated.)

2020-11-24 23:49 UTC, robinlinden commented on src/groups.c
> +        g->name_length = strnlen(g->name, sizeof(g->name) - 1);
strnlen isn't in the C standard. You can (probably) use strnlen_s if uTox targets C11. (Or use strlen since you know g->name always is null-terminated.)

2020-11-24 23:49 UTC, robinlinden commented on src/groups.c
> +static size_t group_get_title_size(Tox *tox, uint32_t group_number) {
const Tox *?

2020-11-24 23:49 UTC, robinlinden commented on src/groups.c
> +    size_t title_size;
This isn't C89. Declare and initialize on the same line.

2020-11-25 00:27 UTC, avoidr commented on src/groups.c
> +GROUPCHAT *group_create(uint32_t group_number, bool av_group, char *name) {
Yes.

2020-11-25 00:28 UTC, avoidr commented on src/groups.c
> +        snprintf((char *)g->name, sizeof(g->name), "Groupchat #%u", group_number);
Right, I should have.

2020-11-25 00:30 UTC, avoidr commented on src/groups.c
> +        g->name_length = strnlen(g->name, sizeof(g->name) - 1);
Drats! You're right, it's only POSIX.1-2008!

Yes, personally I would have left it out, too. Thanks.

2020-11-25 00:30 UTC, avoidr commented on src/groups.c
> +static size_t group_get_title_size(Tox *tox, uint32_t group_number) {
Yes.

2020-11-25 00:35 UTC, avoidr commented on src/groups.c
> +    size_t title_size;
C isn't Python, either. That's the main reason why all of uTox is messy and looks like shit and I get aggressive reading it.

2020-11-25 01:26 UTC, avoidr commented on src/groups.c
> +    size_t title_size;
I don't know if I have the strength to do this.

2020-11-25 01:27 UTC, avoidr commented
By the way, would you const also ints? Or only pointers? And why?

2020-11-30 12:09 UTC, avoidr commented
Rebased.

2020-11-30 13:47 UTC, robinlinden commented
> 
> 
> By the way, would you const also ints? Or only pointers? And why?

I think it's more important to const pointers as changes to them aren't local to the function. If it's a non-const pointer, I'd expect the function to write to it.

2020-12-01 18:11 UTC, avoidr commented
> > By the way, would you const also ints? Or only pointers? And why?
> 
> I think it's more important to const pointers as changes to them aren't local to the function. If it's a non-const pointer, I'd expect the function to write to it.

Ok, right, that's what I thought. I had confused constant pointer with
pointer to constant value. Thanks.

2021-01-17 08:45 UTC, siburec commented
I have tried this branch and I have seen the following:
1. If I create a group with <develop> branch and I change the name, when I build the <group_load_topic> branch I can see the modified name.
2. If I create a new group with <group_load_topic> version, the next time I open utox, the correct name is loaded.
3. However, if create a group with <develop> branch, build <group_load_topic> version and then open utox and change the name, this name is not detected by utox and continues showing Groupchat #x in the next opening.

2021-01-17 08:53 UTC, avoidr commented
You mean `3.` might be a bug? What exactly do you do? Step by step. And what do you expect?

2021-01-17 09:35 UTC, avoidr commented
I think I understand. I will take a look at it later. Thanks.

2021-01-20 21:18 UTC, merged