Create group crash
uTox/uTox pull request #1517
Opened 2021-01-12 16:01 UTC by siburec

Solved a bug in flist.c that caused a crash for some users during the creation of new groups.

2021-01-12 16:10 UTC, siburec commented
This pull request should solve the issues #1437 and #1411. The error is caused because after the memory is reallocated to store a new element, the selected_item was still pointing to the old position. I suppose that depending on the compiler the old memory is freed or not, and that is way only some users encounter this problem.
Unfortunately, although the group is created I am still unable to drag a contact to the group

2021-01-12 18:16 UTC, avoidr commented
Hmm, that's weird, I thought that was already fixed…

Can you please tell me how to reproduce that? And what OS you're running, please, I would like to reproduce.
Thanks.

2021-01-12 18:28 UTC, avoidr commented
By the way, this is a perfect candidate for a second paragraph of a commit message:

>The error is caused because after the memory is reallocated to store a new element, the selected_item was still pointing to the old position. I suppose that depending on the compiler the old memory is freed or not, and that is way only some users encounter this problem.

2021-01-12 20:17 UTC, siburec commented
I am using Ubuntu 20.04 and gcc is on version 9.3. I have compiled following the guide (cmake .., make, sudo checkinstall -y) and I haven't edited any parameter.
In my case, every time I try to create a new group, the program crashes. In the terminal you can see the "out of bounds" message, but it is not really causing the crash. In fact, I still get this error with the patch and the program continues working and creates the group.
If you add -DCMAKE_BUILD_TYPE=Debug, you should see that the error happens in the line switch(i->type) of the page_close() function, because the selected_item is pointing to an old position.

2021-01-13 02:06 UTC, clort81 commented
I pulled latest uTox from master and built with -DCMAKE_BUILD_TYPE=Debug
Avoidr created a group and invited me
``
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 3 receipt_number 2 

Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 4 receipt_number 3 

[New Thread 0xffffe40feef0 (LWP 11502)]
uToxAv:       Trying to end a call when no call is active.
[Thread 0xffffe40feef0 (LWP 11502) exited]
[New Thread 0xffffe3ffdef0 (LWP 11515)]
[Thread 0xffffe3ffdef0 (LWP 11515) exited]
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 5 receipt_number 4 

[New Thread 0xffffe38feef0 (LWP 11562)]
[Thread 0xffffe38feef0 (LWP 11562) exited]
XLib Event:   Type UTF8_STRING || Prop TARGETS 
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 6 receipt_number 5 

XLib Event:   Type UTF8_STRING || Prop TARGETS 
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 2 receipt_number 2 

[New Thread 0xffffe1efeef0 (LWP 11603)]
[Thread 0xffffe1efeef0 (LWP 11603) exited]
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 7 receipt_number 6 

Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 5 receipt_number 3 

XLib Event:   Type UTF8_STRING || Prop TARGETS 
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 6 receipt_number 4 

Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 8 receipt_number 5 

=================================================================
==11465==ERROR: AddressSanitizer: heap-use-after-free on address 0xfffff044b048 at pc 0xaaaaaab3a9c8 bp 0xffffffffed20 sp 0xffffffffed38
READ of size 4 at 0xfffff044b048 thread T0
    #0 0xaaaaaab3a9c4 in page_close /pr/uTox/src/flist.c:384
    #1 0xaaaaaab3a9c4 in show_page /pr/uTox/src/flist.c:617
    #2 0xaaaaaab697cc in flist_select_last /pr/uTox/src/flist.c:935
    #3 0xaaaaaab697cc in utox_message_dispatch /pr/uTox/src/utox.c:613
    #4 0xaaaaaab78094 in doevent /pr/uTox/src/xlib/event.c:691
    #5 0xaaaaaab28ec4 in doevent /pr/uTox/src/xlib/event.c:267
    #6 0xaaaaaab28ec4 in main /pr/uTox/src/xlib/main.c:855
    #7 0xfffff6c0f214 in __libc_start_main ../csu/libc-start.c:308
    #8 0xaaaaaab29c3c  (/media/sd/pcbak2/Projects/uTox/build/utox+0x89c3c)

0xfffff044b048 is located 40 bytes inside of 96-byte region [0xfffff044b020,0xfffff044b080)
freed by thread T0 here:
    #0 0xfffff75b81c4 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0xaaaaaab394fc in newitem /pr/uTox/src/flist.c:286
    #2 0xaaaaaab69708 in flist_add_group /pr/uTox/src/flist.c:718
    #3 0xaaaaaab69708 in utox_message_dispatch /pr/uTox/src/utox.c:612
    #4 0xaaaaaab78094 in doevent /pr/uTox/src/xlib/event.c:691
    #5 0xaaaaaab28ec4 in doevent /pr/uTox/src/xlib/event.c:267
    #6 0xaaaaaab28ec4 in main /pr/uTox/src/xlib/main.c:855
    #7 0xfffff6c0f214 in __libc_start_main ../csu/libc-start.c:308
    #8 0xaaaaaab29c3c  (/media/sd/pcbak2/Projects/uTox/build/utox+0x89c3c)

previously allocated by thread T5 here:
    #0 0xfffff75b800c in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0xaaaaaab39810 in flist_start /pr/uTox/src/flist.c:639
    #2 0xaaaaaab59cc0 in toxcore_thread /pr/uTox/src/tox.c:509
    #3 0xfffff72ea624 in start_thread nptl/pthread_create.c:477
    #4 0xfffff6cc1018  (/lib/aarch64-linux-gnu/libc.so.6+0xd6018)

Thread T5 created by T0 here:
    #0 0xfffff756b9b0 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:214
    #1 0xaaaaaab7ce68 in thread /pr/uTox/src/xlib/main.c:220
    #2 0xaaaaaab28e34 in main /pr/uTox/src/xlib/main.c:849
    #3 0xfffff6c0f214 in __libc_start_main ../csu/libc-start.c:308
    #4 0xaaaaaab29c3c  (/media/sd/pcbak2/Projects/uTox/build/utox+0x89c3c)

SUMMARY: AddressSanitizer: heap-use-after-free /pr/uTox/src/flist.c:384 in page_close
Shadow bytes around the buggy address:
  0x200ffe0895b0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe0895c0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe0895d0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe0895e0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe0895f0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
=>0x200ffe089600: fa fa fa fa fd fd fd fd fd[fd]fd fd fd fd fd fd
  0x200ffe089610: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x200ffe089620: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x200ffe089630: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x200ffe089640: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x200ffe089650: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==11465==ABORTING
[Thread 0xffffe71fcef0 (LWP 11477) exited]
[Thread 0xffffe72fdef0 (LWP 11476) exited]
[Thread 0xffffe73feef0 (LWP 11475) exited]
[Thread 0xffffeaf2cef0 (LWP 11472) exited]
[Thread 0xffffeb72def0 (LWP 11471) exited]
[Thread 0xffffec72fef0 (LWP 11468) exited]
[Thread 0xfffff67f0460 (LWP 11465) exited]
[Inferior 1 (process 11465) exited with code 01]
``
Running on aarch64, 
gcc version 10.2.1 20201224 (Debian 10.2.1-3) 
I had no other groups active.  
If I can provide more info, let me know.

2021-01-13 02:13 UTC, clort81 commented
Another crash log - bt full gives 'No stack'
```
uTox Audio:   Audio out device set to null.
[Thread 0xffffebf2eef0 (LWP 11840) exited]
Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 3 receipt_number 1 

Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 4 receipt_number 2 

Messages:     Messages:	Unable to update this message...
		msg->disk_offset 0 && m->number 6 receipt_number 3 

get_group:     index: 0 is out of bounds.
=================================================================
==11837==ERROR: AddressSanitizer: heap-use-after-free on address 0xfffff044b020 at pc 0xaaaaaab3a9c8 bp 0xffffffffed20 sp 0xffffffffed38
READ of size 4 at 0xfffff044b020 thread T0
    #0 0xaaaaaab3a9c4 in page_close /pr/uTox/src/flist.c:384
    #1 0xaaaaaab3a9c4 in show_page /pr/uTox/src/flist.c:617
    #2 0xaaaaaab697cc in flist_select_last /pr/uTox/src/flist.c:935
    #3 0xaaaaaab697cc in utox_message_dispatch /pr/uTox/src/utox.c:613
    #4 0xaaaaaab78094 in doevent /pr/uTox/src/xlib/event.c:691
    #5 0xaaaaaab28ec4 in doevent /pr/uTox/src/xlib/event.c:267
    #6 0xaaaaaab28ec4 in main /pr/uTox/src/xlib/main.c:855
    #7 0xfffff6c0f214 in __libc_start_main ../csu/libc-start.c:308
    #8 0xaaaaaab29c3c  (/media/sd/pcbak2/Projects/uTox/build/utox+0x89c3c)

0xfffff044b020 is located 0 bytes inside of 88-byte region [0xfffff044b020,0xfffff044b078)
freed by thread T0 here:
    #0 0xfffff75b81c4 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0xaaaaaab394fc in newitem /pr/uTox/src/flist.c:286
    #2 0xaaaaaab69708 in flist_add_group /pr/uTox/src/flist.c:718
    #3 0xaaaaaab69708 in utox_message_dispatch /pr/uTox/src/utox.c:612
    #4 0xaaaaaab78094 in doevent /pr/uTox/src/xlib/event.c:691
    #5 0xaaaaaab28ec4 in doevent /pr/uTox/src/xlib/event.c:267
    #6 0xaaaaaab28ec4 in main /pr/uTox/src/xlib/main.c:855
    #7 0xfffff6c0f214 in __libc_start_main ../csu/libc-start.c:308
    #8 0xaaaaaab29c3c  (/media/sd/pcbak2/Projects/uTox/build/utox+0x89c3c)

previously allocated by thread T5 here:
    #0 0xfffff75b800c in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0xaaaaaab39810 in flist_start /pr/uTox/src/flist.c:639
    #2 0xaaaaaab59cc0 in toxcore_thread /pr/uTox/src/tox.c:509
    #3 0xfffff72ea624 in start_thread nptl/pthread_create.c:477
    #4 0xfffff6cc1018  (/lib/aarch64-linux-gnu/libc.so.6+0xd6018)

Thread T5 created by T0 here:
    #0 0xfffff756b9b0 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:214
    #1 0xaaaaaab7ce68 in thread /pr/uTox/src/xlib/main.c:220
    #2 0xaaaaaab28e34 in main /pr/uTox/src/xlib/main.c:849
    #3 0xfffff6c0f214 in __libc_start_main ../csu/libc-start.c:308
    #4 0xaaaaaab29c3c  (/media/sd/pcbak2/Projects/uTox/build/utox+0x89c3c)

SUMMARY: AddressSanitizer: heap-use-after-free /pr/uTox/src/flist.c:384 in page_close
Shadow bytes around the buggy address:
  0x200ffe0895b0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe0895c0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe0895d0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe0895e0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe0895f0: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fa
=>0x200ffe089600: fa fa fa fa[fd]fd fd fd fd fd fd fd fd fd fd fa
  0x200ffe089610: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x200ffe089620: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x200ffe089630: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x200ffe089640: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x200ffe089650: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==11837==ABORTING
[Thread 0xffffe71fcef0 (LWP 11847) exited]
[Thread 0xffffe72fdef0 (LWP 11846) exited]
[Thread 0xffffe7cfeef0 (LWP 11844) exited]
[Thread 0xffffeaf2cef0 (LWP 11842) exited]
[Thread 0xffffeb72def0 (LWP 11841) exited]
[Thread 0xffffec72fef0 (LWP 11838) exited]
[Thread 0xfffff67f0460 (LWP 11837) exited]
[Inferior 1 (process 11837) exited with code 01]
(gdb) bt full
No stack.
```

2021-01-13 07:22 UTC, siburec commented
Hi @clort81, your error is happening in the same line as the one I mentioned. Could you download the develop branch and apply my proposed change to see if it gets solved?

2021-01-13 20:22 UTC, Serphentas commented
@siburec I just tried compiling but it keeps asking for minini and qrcodegen while I've installed the -dev packages on Ubuntu. Any ideas ?

2021-01-13 21:47 UTC, avoidr commented
@siburec This is the right approach and I didn't run the code but it should be correct. I'll think a little bit more, then test. In the meantime, do you want to change your commit at all, or shall I do that for you? There are at least style issues (space around operators, space after ';').

@Serphentas You probably need the third patch here: https://sources.debian.org/patches/utox/0.18.0-1/
Or you clone the git subrepositories.

2021-01-13 21:49 UTC, avoidr commented
@clort81 Thanks for the backtraces, it was very helpful!

2021-01-14 07:51 UTC, siburec commented
@avoidr I have only added some style corrections, but I am not sure if it matches your style. Do you have any guideline document ?

Regarding the last modification, I have accidentally had to commit twice and I don't know how to join them.

2021-01-14 09:39 UTC, avoidr commented
Do you use `git` the command line tool? You can 'squash' commits together with `git rebase -i HEAD~2` (for the last two commits relative to your current checkout) and then marking the second commit as "squash". You can squash the comment away now.

But generally, I think pushing new commits in PRs are better than force-rewriting the branch, because I can see the progress and the changes better. Technically I'd need to be skeptical of the whole PR anew if you rewrite it. And in the end, those little progress steps can still easily be squashed together.

We don't have a style guide, sorry. You'll have to guess the "style" of the surrounding code.

Thanks.

2021-01-14 09:47 UTC, avoidr requested changes

2021-01-14 09:47 UTC, avoidr commented on src/flist.c
> +    if (item_pos>=0){
Spaces around operator, please.

2021-01-14 09:47 UTC, avoidr commented on src/flist.c
> +    int item_pos = -1;
Rename to `old_selected`?

2021-01-14 16:00 UTC, siburec commented on src/flist.c
> +    int item_pos = -1;
I have added your last comments to a new commit. I haven't been able to join the commits, so I'll leave it so, but feel free to do it if you want to have a clearer history.

2021-01-14 23:54 UTC, avoidr commented
Made some more changes. I'll review myself later again. Thanks.

2021-01-15 00:02 UTC, avoidr approved these changes, later dismissed

2021-01-15 00:06 UTC, Serphentas commented
> @Serphentas You probably need the third patch here: https://sources.debian.org/patches/utox/0.18.0-1/
> Or you clone the git subrepositories.

Thanks, full recursive clone did the trick. However, still getting the issue. Would you like a debug log ?

2021-01-15 00:44 UTC, avoidr commented
@Serphentas Feel free to open an issue!

2021-01-15 01:33 UTC, Serphentas commented
Nevermind, I forgot to do something on my end which led me to discover another bug :)) Thanks for this PR @siburec

2021-01-16 01:36 UTC, avoidr commented
I believe this is the final version now. If you could test, that would be great. Thanks.

2021-01-16 14:47 UTC, siburec commented
I have tried your last version and it is still working fine.

2021-01-16 15:15 UTC, avoidr commented
> I have tried your last version and it is still working fine.

Awesome! Then I'll merge later today.

2021-01-17 00:54 UTC, merged

2021-01-17 01:01 UTC, avoidr commented
Merged, thanks!

If you (all of you) want, you can test #1492, that would be cool. I don't see any flaw, but it's always good to be confirmed.
Thanks!

2021-01-17 01:04 UTC, avoidr commented
Right, what #1492 does is load the group titles from the Tox save/profile. The titles are always saved, just uTox hadn't loaded them before. So if you make a group and set a title, when you restart uTox, the titles should be the same as last time instead of just "Groupchat #n").

2021-01-17 08:38 UTC, siburec commented
> Right, what #1492 does is load the group titles from the Tox save/profile. The titles are always saved, just uTox hadn't loaded them before. So if you make a group and set a title, when you restart uTox, the titles should be the same as last time instead of just "Groupchat #n").

I will respond in the other issue to keep better track of the comments.

2021-01-23 09:17 UTC, zoff99 commented
@siburec good catch, thanks for this PR